name: Isle of Cinder
size: [16, 16]
seed: 123456
landmass:
  percent: 0.60
  shape: "island"           # island | blob | archipelago (future)
  falloff: 1.8              # radial falloff exponent
biomes:
  land_primary: "Plains"
  land_secondary: "Forest"
  water: "Coast"
features:
  volcano:
    ensure: true
    center_bias: 0.7        # 0..1 toward center
  settlements:
    count: 3
    min_distance: 3
    prefer_biomes: ["Plains","Forest"]
  ports:
    count: 3
    coastline_only: true
spawn:
  prefer_biomes: ["Plains","Forest"]
